### ISSUE TITLE
Defender ST-7 Skynet Italia incorrect format

### ISSUE THREAD

**Issue by drageloth** [schmupu/ioBroker.contactid#13]
**Describe the bug**  
Not a bug really, but different messaging for another alarm

**To Reproduce**  
Actually you have to buy one to see the messaging.

**Expected behavior**  
The alarm should sent its id first but instead it sends it last

**Screenshots & Logfiles**  
Log from iobroker: (ip addresses are wrong for the obvious reasons)

contactid.0 | 2020-02-15 17:20:11.992 | info | (18233) 10.10.10.10:3635 sending following message: 9701002F"ADM-CID"2222R0L0#13E3186[#13E3186\|1302 01 000]
contactid.0 | 2020-02-15 17:20:11.986 | info | (18233) connection from 10.10.10.10:3634 closed
contactid.0 | 2020-02-15 17:20:11.984 | info | (18233) 10.10.10.10:3634 sending following message: 9776002F"ADM-CID"2221R0L0#13E3186[#13E3186\|1302 01 000]
contactid.0 | 2020-02-15 17:20:11.978 | info | (18233) connection from 10.10.10.10:3633 closed
contactid.0 | 2020-02-15 17:20:11.976 | info | (18233) 10.10.10.10:3633 sending following message: 575A002F"ADM-CID"2220R0L0#13E3186[#13E3186\|1302 01 000]
contactid.0 | 2020-02-15 17:20:11.971 | info | (18233) connection from 10.10.10.10:3632 closed
contactid.0 | 2020-02-15 17:20:11.969 | info | (18233) 10.10.10.10:3632 sending following message: 705F002F"ADM-CID"2219R0L0#13E3186[#13E3186\|1302 01 000]

**Versions:**  
 - Adapter version: <1.0.0>
 - JS-Controller version: <js-controller-version>  2.2.8
 - Node version: <node-version>  10.19.0
 - Operating system: ubuntu 18.04 headless (container on proxmox). Its a fresh install with nothing else on it. Not even another adapter

**Additional context**  
The username (or userid if you may) is 13E3186
You can see it sends it last along with some numbers in brackets. I don't know if it's from the alarm or from the log of broker since it's the first time I use it and I set it up only for getting messages from the alarm and send on telegram if something bad happens. It won't do anything else.
Apart from the formatting which is incorrect and I assume that's the reason it gets disconnected, it also floods the broker with reports. And I mean it FLOODS with messages. For about 3-4 minutes it had 4-5.000 messages. Is that normal? The alarm was armed and not doing anything.

Thanks in advance!

edit: in the CMS setting of the alarm, it has the following : 
Server Address: 10.10.10.11 (the address of the broker)
Server Port: 50000
ID account: 13E3186
Password:
Heartbeat times(1-255s): 60
I've left the password empty on purpose since it wouldn't work anyway with your adapter. I assume the rest are okay. (?)

**Comment by drageloth** [comment]
Closing this issue. It doesn't work with this adapter although the alarm supports CID IP, but works with the SIA adapter. So doesn't need fixing since we can do it with another one.

**Comment by schmupu** [comment]
Okay, I would always suggest the SIA Adaper.
