### ISSUE TITLE
ACK-invalid Format

### ISSUE THREAD

**Issue by MacAgent** [schmupu/ioBroker.contactid#14]
My Lupusec XT2 (incl. Dongle) does not receive a correct ACK message and repeat sending the CID message 

XT2 Config: ip://CID1@192.168.x.2:2001/CID

ioBrocker.contactid Subcirber: CID1
ioBrocker.contactid Subcirber: Lupusec XT2 (and alternatively tested as Lupusec XT2 Plus) 

ioBroker Log: contactid.0 | <date&time> | 192.168.x.1:48646 sending following message: [CID2 181401010012843]

XT2 Event Log: Error | Reporter | url='ip://CID1@192.168.x.2:5000/CID', ret=-404, reason='**ACK-ungültiges Format**', event=760, text='Area 0 Zone 0 : Home Automation'

**Comment by schmupu** [comment]
Could you please test the Lupusec Adapter version 1.0.2 from GitHub. Does it work?

How to load a version from GitHub: http://www.stueben.de/iobroker-adapter-per-github-laden/

**Comment by MacAgent** [comment]
I confirm that "Contact ID Server für Alarmanlagen" version 1.0.2 is working and the my XT2 is now receiving the correct ACK messages. 

ContactID messages are now acknowledged as successfully send.

Thank you very much for quit and easy fix
