### ISSUE TITLE
Please implement discovery function

### ISSUE THREAD

**Issue by GermanBluefox** [schmupu/ioBroker.contactid#2]
Like here: https://github.com/ioBroker/ioBroker.discovery/blob/master/lib/adapters/fhem.js

**Comment by schmupu** [comment]
it is not possible to add this adapter to discovery Modus. The adapter listen on a port for incoming messages from an alarm system. You configure in the contactid adapter the port you are listening. For example port 50000.  Now you have to add the IP address of ioBroker and the contactid port of the adapter (in this example 50000) to alarm system configuration.
